#!/usr/bin/env bash
# Auto-generated by ollama-manager — do not edit manually
# Source this file:  source ./ollama-switch.sh

export OLLAMA_API_KEY="test"
export ANTHROPIC_API_KEY="test"
export ANTHROPIC_BASE_URL="https://ollama.com"
export ANTHROPIC_AUTH_TOKEN="test"

echo "✓ Switched OLLAMA_API_KEY + ANTHROPIC_* vars in current shell"
echo "  Launching: ollama launch claude --model gemma4:31b-cloud"
ollama launch claude --model gemma4:31b-cloud
