#!/usr/bin/env bash
# Auto-generated by ollama-manager — do not edit manually
# Source this file:  source ./ollama-switch.sh

export OLLAMA_API_KEY="ad272a9d731b4c9fa3c344fa2084162f.voejMMqvWZUSsDlwZyZDCE2H"
export ANTHROPIC_API_KEY="ad272a9d731b4c9fa3c344fa2084162f.voejMMqvWZUSsDlwZyZDCE2H"
export ANTHROPIC_BASE_URL="https://ollama.com"
export ANTHROPIC_AUTH_TOKEN="ad272a9d731b4c9fa3c344fa2084162f.voejMMqvWZUSsDlwZyZDCE2H"

echo "✓ Switched OLLAMA_API_KEY + ANTHROPIC_* vars in current shell"
echo "  Launching: ollama launch claude --model gemma4:31b-cloud"
ollama launch claude --model gemma4:31b-cloud
