import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WRAPPER = path.join(__dirname, "..", "ollama-switch.sh");

export function writeLaunchScript(apiKey: string, model: string): string {
  /**
   * Why a shell wrapper instead of spawn()?
   *
   * Node's process.env changes are local to the Node process.
   * When Node exits, the parent shell's env is untouched.
   * So `export OLLAMA_API_KEY=x` inside Node → dead on exit.
   *
   * Solution: write a .sh file the user sources (or we exec directly).
   * `source ollama-switch.sh` runs in the CURRENT shell → env persists.
   *
   * Ollama Cloud needs OLLAMA_API_KEY.
   * Claude Code (via ollama launch claude) needs:
   *   ANTHROPIC_BASE_URL  → where to find the Anthropic-compatible API
   *   ANTHROPIC_API_KEY   → set to the Ollama key (or "ollama" for local)
   */
  const script = `#!/usr/bin/env bash
# Auto-generated by ollama-manager — do not edit manually
# Source this file:  source ./ollama-switch.sh

export OLLAMA_API_KEY="${apiKey}"
export ANTHROPIC_API_KEY="${apiKey}"
export ANTHROPIC_BASE_URL="https://ollama.com"
export ANTHROPIC_AUTH_TOKEN="${apiKey}"

echo "✓ Switched OLLAMA_API_KEY + ANTHROPIC_* vars in current shell"
echo "  Launching: ollama launch claude --model ${model}"
ollama launch claude --model ${model}
`;

  fs.writeFileSync(WRAPPER, script, { mode: 0o755 });
  return WRAPPER;
}
